'use strict';
const C=window.MAQAM_CONTENT;
const E=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const project=C.projects.find(p=>p.slug===document.body.dataset.project);
const arrow='<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg>';
const logo=`<span class="wordmark company-wordmark">Maqam Engineering<span class="company-wordmark-sub">Projects SPC</span><span class="company-wordmark-ar" lang="ar" dir="rtl">${E(C.company.arabic)}</span></span>`;
const mark='<span class="logo-art"><img src="../assets/brochure/maqam-logo.png" alt="MEP — Maqam Engineering Projects logo" width="391" height="396"></span>';
if(!project){document.getElementById('project-app').innerHTML='<main class="detail-empty"><h1>Service not found</h1><p><a href="../index.html#projects">Return to the service portfolio</a></p></main>';}else{
 document.title=project.name+' | Maqam Engineering Projects SPC';
 document.querySelector('meta[name="description"]').setAttribute('content',project.description);
 const isWork=project.type==='completed';
 if(isWork){
  project.title=project.title.split(' · ')[0];
  project.alt=project.title;
  project.gallery=project.gallery.map((photo,i)=>({...photo,caption:project.title+' · Photo '+(i+1)}));
  project.priorities=project.priorities.filter(x=>x!==project.location);
  for(const key of ['description','overview'])project[key]=project[key].replace(' at '+project.location,'').replace(' — '+project.location,'').replace(' · '+project.location,'');
  document.querySelector('meta[name="description"]').setAttribute('content',project.description);
 }
 const enquiry='../index.html?scope='+encodeURIComponent(project.slug)+'#contact';
 document.getElementById('project-app').innerHTML=`
 <a class="skip-link" href="#project-main">Skip to details</a>
 <header class="site-header"><div class="nav-inner"><a class="brand" href="../index.html" aria-label="Maqam Engineering home">${logo}</a><nav class="detail-nav" aria-label="Service navigation"><a href="../index.html#projects">← All projects</a><a class="detail-nav-contact" href="${enquiry}">Discuss this scope ${arrow}</a></nav><a class="header-mark" href="../index.html" aria-label="Maqam home">${mark}</a></div></header>
 <main id="project-main"><section class="detail-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="../index.html">Home</a><span aria-hidden="true">/</span><a href="../index.html#projects">${isWork?'Projects':'Service portfolio'}</a><span aria-hidden="true">/</span><span aria-current="page">${E(project.name)}</span></nav><p class="eyebrow"><span></span>${E(project.name)}</p><h1>${E(project.title)}</h1><p class="detail-summary">${E(project.overview)}</p><span class="detail-status">${isWork?E(project.status):'Service portfolio · Company brochure'}</span></div></section>
 <section class="detail-section" aria-label="Service scope and photographs"><div class="container"><div class="detail-image"><img src="../${E(project.image)}" alt="${E(project.alt)}" width="1200" height="750"><span>${E(project.name)}</span></div><div class="detail-columns"><div class="detail-copy"><p class="eyebrow"><span></span>${isWork?'PROJECT SCOPE':'SERVICES & PRODUCTS'}</p>${project.groups.map((group,i)=>`<section class="scope-group" aria-labelledby="group-${i}"><h3 id="group-${i}">${E(group.title)}</h3><ul class="detail-list">${group.items.map(x=>`<li>${E(x)}</li>`).join('')}</ul></section>`).join('')}<section><h2>${isWork?'Project overview':'Areas of support'}</h2><div class="priority-tags">${project.priorities.map(x=>`<span>${E(x)}</span>`).join('')}</div></section></div><aside class="detail-aside"><h2>Discuss your requirements</h2><dl>${isWork?`<div><dt>Client</dt><dd>${E(project.client)}</dd></div><div><dt>Period / duration</dt><dd>${E(project.timing)}</dd></div><div><dt>Status</dt><dd>${E(project.status)}</dd></div>`:''}<div><dt>Service area</dt><dd>${E(project.name)}</dd></div><div><dt>Based in</dt><dd>Al Hail South, Muscat, Oman</dd></div><div><dt>Contact</dt><dd>${E(C.company.contact)}<br>${E(C.company.department)}</dd></div></dl><p>Share your specifications, site requirements and delivery needs so we can discuss a suitable scope of support.</p><a class="button button-gradient" href="${enquiry}">Enquire about this service ${arrow}</a><a class="detail-email" href="mailto:${E(C.company.email)}">${E(C.company.email)}</a><a class="detail-email" href="tel:${E(C.company.phone.replace(/\s/g,''))}">${E(C.company.phone)}</a></aside></div><section class="detail-gallery" aria-labelledby="photos-title"><h2 id="photos-title">${isWork?'Project photographs':E(project.name)+' in pictures'}</h2><p>${isWork?'Photographs from the project record.':'Photographs and product visuals illustrating our service capabilities.'}</p><div class="brochure-photo-grid">${project.gallery.map(photo=>`<figure><img src="../${E(photo.image)}" alt="${E(photo.caption)}" loading="lazy" width="900" height="675"><figcaption>${E(photo.caption)}</figcaption></figure>`).join('')}</div></section><a class="text-link detail-back" href="../index.html#projects">← Back to projects</a></div></section></main>
 <footer><div class="container"><div class="footer-top"><a class="footer-brand" href="../index.html" aria-label="Maqam home">${mark}${logo}</a><div><p>${E(C.company.address)}</p><a href="mailto:${E(C.company.email)}">${E(C.company.email)}</a></div><a href="${enquiry}">Contact us ${arrow}</a></div><div class="footer-bottom"><p>© 2026 Maqam Engineering Projects SPC. All rights reserved.</p><span lang="ar" dir="rtl">${E(C.company.arabic)}</span><a href="../index.html#projects">All projects ${arrow}</a></div></div></footer>`;
}
